spring:
  datasource:
    url: jdbc:h2:mem:doctorsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # or create-drop
    show-sql: true
  sql:
    init:
      mode: always   
