spring:
  datasource:
    url: jdbc:h2:~/Downloads/spring-microservice-level-5/doctor-service/database/doctorsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # or create-drop
    show-sql: true
  sql:
    init:
      mode: always   
