spring:  
  datasource:
    url: jdbc:h2:file:./data/patientsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # or create-drop
    show-sql: true
  sql:
    init:
      mode: always   
